<Project>
    <PropertyGroup>
        <LangVersion>latest</LangVersion>
        <Version>2025.9</Version>
        <EdsSharedVersion>2025.9.29</EdsSharedVersion>
        <HsnSoftFrameworkVersion>2025.9.8</HsnSoftFrameworkVersion>
        <MicrosoftAspNetCorePackageVersion>9.0.8</MicrosoftAspNetCorePackageVersion>
        <MicrosoftEntityFrameworkCorePackageVersion>9.0.8</MicrosoftEntityFrameworkCorePackageVersion>
    </PropertyGroup>
</Project>