<Project Sdk="Microsoft.NET.Sdk">

    <Import Project="..\..\common.version.props" />
    <Import Project="..\..\common.props" />

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <PackageId>Eds.IdentityService.Application</PackageId>
        <RootNamespace>Eds.IdentityService.Application</RootNamespace>
        <Title>HsnSoft Eds Identity Service Application</Title>
        <Description>HsnSoft Eds Identity Service Application</Description>
        <PackageTags>HsnSoft Eds Identity Service Application</PackageTags>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="HsnSoft.Base.Ddd.Application" Version="$(HsnSoftFrameworkVersion)" />
        <PackageReference Include="HsnSoft.Base.Authorization" Version="$(HsnSoftFrameworkVersion)" />
        <PackageReference Include="HsnSoft.Base.AutoMapper" Version="$(HsnSoftFrameworkVersion)" />
        <!--<ProjectReference Include="..\..\..\..\..\..\hsn-soft\base-framework\src\HsnSoft.Base.Ddd.Application\HsnSoft.Base.Ddd.Application.csproj" />-->
        <!--<ProjectReference Include="..\..\..\..\..\..\hsn-soft\base-framework\src\HsnSoft.Base.Authorization\HsnSoft.Base.Authorization.csproj" />-->
        <!--<ProjectReference Include="..\..\..\..\..\..\hsn-soft\base-framework\src\HsnSoft.Base.AutoMapper\HsnSoft.Base.AutoMapper.csproj" />-->
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Eds.Shared.Contracts" Version="$(EdsSharedVersion)" />
        <!--<ProjectReference Include="..\..\..\..\shared\src\Eds.Shared.Contracts\Eds.Shared.Contracts.csproj" />-->
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Eds.IdentityService.Domain\Eds.IdentityService.Domain.csproj" />
    </ItemGroup>

</Project>